version: "3.3"
services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    ports:
      - 8081:8080
    volumes:
      - /location/of/trainingData:/usr/share/tesseract-ocr/5/tessdata
      - /location/of/extraConfigs:/configs
      - /location/of/customFiles:/customFiles/
      - /location/of/logs:/logs/
    environment:
      - DOCKER_ENABLE_SECURITY=false