version: '3'

services:
  nextcloud:
    image: nextcloud
    ports:
      - 8080:80
    volumes:
      - ./nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=nextcloud-db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=0901
    depends_on:
      - nextcloud-db

  nextcloud-db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=0901
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=0901
    volumes:
      - ./db:/var/lib/mysql